nevermined-io/node

package.json
yarn.lock

release v0.3.0

---

.github/workflows/test.yml
package.json
yarn.lock

Updating sdk version

---

package.json
src/shared/nevermined/nvm.service.ts

- get filename from ddo by default if defined
- bump to version 0.4.3
Related to Issue https://github.com/nevermined-io/node/issues/44

Fix filename when downloading

---

.github/workflows/test.yml
src/access/access.controller.ts
src/shared/nevermined/nvm.service.ts

When downloading data, try to decrypt files that were encrypted in DTP flow.
Related to Issue https://github.com/nevermined-io/contracts/issues/407

decrypt encrypted files

---

src/shared/nevermined/nvm.service.ts

Fixing DTP returns

---

package.json
src/access/access.controller.ts
src/auth/auth.service.ts
src/encrypt/encrypt.controller.ts
src/encrypt/encrypt.integration.spec.ts
src/shared/nevermined/nvm.service.ts
yarn.lock

Update sdk dtp 0.3.0 rc5

---

package.json
yarn.lock

Update/sdk dtp 0.3.0 rc10

---

.github/dependabot.yml
.github/workflows/testing.yml
config/nevermined.js
src/info/info.integration.spec.ts

- Tests running using new nvm-tools

feat: use new nvm-tools for tests

---

package.json
src/shared/nevermined/nvm.service.ts

checks if an s3 bucket exists before uploading a file. If not, if will create it

check if s3 bucket exits before upload data

---

docs/_header.md
docs/openapi.json

adds brief description of compute capabilities and updates the openapi json file

added compute documentation

---

src/subscriptions/subscriptions.service.ts

It fixes a bug introduced by #126 related with the new way to calculate expiration time of subscriptions
Related to Issue #126

fix: current date is not necessary

---

package.json

* update sdk to `1.3.0` version 
* update sdk-dtp to `0.4.2` version

feat: update sdk and sdk-dtp version

---

.github/workflows/testing-integration.yml
.github/workflows/testing-nightly.yml
argo-workflows-templates/nvm-compute-template-geth-localnet.yaml
package.json

Using latest sdk and compute pods

---

src/access/access.controller.ts
src/shared/nevermined/nvm.service.ts

- Improved error responses from /nft-transfer
Related to Issue https://github.com/nevermined-io/node/issues/138

fix: non-subscription nfts have no duration field

---

package.json

- update  sdk
- update sdk-dtp
- bump version to 1.2.0

feat: update to latest sdk

---

integration/subscriptions.integration.spec.ts
package.json
scripts/download-artifacts.sh
src/access/access.controller.ts
src/shared/nevermined/nvm.service.ts

remove props that subgraph does not return.

fix: remove props that subgraph does not return

---

package.json

Using sdk v1.3.7 and sdk-dtp v0.4.8

---

package.json
src/access/access.controller.ts
src/shared/nevermined/nvm.service.ts
src/subscriptions/subscriptions.service.ts

- log errors
- bump version to 1.2.8

feat: log errors

---

.github/workflows/testing-integration.yml
integration/config.ts
package.json
src/access/access.controller.ts

I think this is a safer way of checking if the agreement exists because it checks on all templates

fix: check if agreement on chain exists should respect the template

---

package.json
yarn.lock

feat: update to sdk v1.4.0

---

package.json

fix: run right profile

---

package.json

feat: update sdk to 1.5.2

---

package.json
src/main.ts

feat: increase log level

---

package.json
src/shared/nevermined/nvm.service.ts

Related to Issue https://github.com/nevermined-io/node/issues/208

fix: bug getting the block number with the updated subgraphs

---

.github/workflows/testing-integration.yml
.github/workflows/testing.yml
integration/subscriptions.integration.spec.ts
package.json
src/access/access.controller.ts
src/auth/auth.service.spec.ts
src/auth/auth.service.ts
src/info/info.controller.ts
src/shared/nevermined/nvm.service.ts
src/subscriptions/subscriptions.service.ts
yarn.lock

feat: update sdk to version 2.0.0-rc0

---

package.json
src/shared/nevermined/nvm.service.ts
src/subscriptions/subscriptions.controller.ts
src/subscriptions/subscriptions.service.ts
yarn.lock

fix: improving credits flows

---

.github/workflows/testing-integration.yml
integration/resources/NFT1155SubscriptionUpgradeable.json
integration/subscriptions.integration.spec.ts
integration/utils.ts
package.json
src/subscriptions/subscriptions.controller.ts
src/subscriptions/subscriptions.service.ts
yarn.lock

fixes jwt generation for ERC1155 flows

Fix NFT 1155 JWT generation when multiple subscriptions

---

package.json
src/auth/auth.service.ts
src/shared/nevermined/nvm.service.ts

Better credits balance check to conform the usage conditions defined in the access service

fix: better check of balance taking into account dynamic payment attributes

---

package.json
src/subscriptions/subscriptions.controller.ts
src/subscriptions/subscriptions.service.ts
yarn.lock

fix: owner can download using credit subscriptions

---

package.json

feat: update sdk v2.0.7

---

README.md
config/from-env.js
package.json
src/access/access.controller.ts
src/auth/auth.service.ts
src/info/info.controller.ts
src/shared/config/config.service.ts
src/shared/nevermined/nvm.service.ts
yarn.lock

- SCW through zerodev can be activated by setting the ZERODEV_PROJECT_ID optional env
Closes https://github.com/nevermined-io/internal/issues/575

feat: added support for smart contract wallets through zerodev

---

package.json
src/shared/nevermined/nvm.service.ts
yarn.lock

fix: node use sdk v2.2.4 with profiles reduced

---

package.json
yarn.lock

feat: update sdk

---

package.json
src/subscriptions/subscriptions.service.ts
yarn.lock

Fix: Service type validation

---

package.json

feat: upgrade sdk

---

.gitignore
package.json
src/common/helpers/encryption.helper.ts
yarn.lock

feat: force conversion

---

.gitignore
package.json
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/common/guards/auth/session-key.guard.ts
src/common/helpers/jwt.utils.ts
src/shared/backend/backend.service.ts
yarn.lock

Related to Issue https://github.com/nevermined-io/sdk-js/issues/657

feat: update node to support download with session keys

---

package.json
yarn.lock

feat: update version

---

package.json
src/access/access.controller.ts

Fixes an incorrect notifications plan URL
Related to Issue https://github.com/nevermined-io/one/issues/1609

Fix: Plan URL

---

package.json
yarn.lock

feat: support base sepolia with sdk 3.1.2
